import type { CategoryTile, GalleryImage, HomeProduct, Review, Slide } from '@/types/home';

export const heroSlides: Slide[] = [
  {
    id: 'midnight-caramel',
    eyebrow: 'Limited batch',
    title: 'Midnight caramel popcorn for movie nights.',
    description: 'Air-popped kernels glazed with deep caramel, sea salt, and a velvet cocoa finish.',
    image:
      'https://images.unsplash.com/photo-1578849278619-e73505e9610f?auto=format&fit=crop&w=1600&q=85',
    ctaLabel: 'Shop popcorn',
    href: '/products?category=popcorn',
  },
  {
    id: 'festival-combo',
    eyebrow: 'Combo offers',
    title: 'Snack boxes that make gifting dangerously easy.',
    description: 'Curated sweet, spicy, and crunchy bundles packed for birthdays, teams, and festivals.',
    image:
      'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?auto=format&fit=crop&w=1600&q=85',
    ctaLabel: 'Explore combos',
    href: '/products?collection=combos',
  },
  {
    id: 'protein-trail',
    eyebrow: 'New arrival',
    title: 'Trail mixes built for the desk, gym, and road.',
    description: 'Roasted nuts, seeds, berries, and chocolate notes in resealable everyday packs.',
    image:
      'https://images.unsplash.com/photo-1599599810694-b5b37304c041?auto=format&fit=crop&w=1600&q=85',
    ctaLabel: 'Try new mixes',
    href: '/products?tag=new-arrivals',
  },
];

export const categories: CategoryTile[] = [
  {
    id: 'popcorn',
    name: 'Gourmet Popcorn',
    itemCount: 18,
    image:
      'https://images.unsplash.com/photo-1578849278619-e73505e9610f?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'chips',
    name: 'Crisps & Chips',
    itemCount: 24,
    image:
      'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'nuts',
    name: 'Nuts & Trail Mix',
    itemCount: 16,
    image:
      'https://images.unsplash.com/photo-1599599810694-b5b37304c041?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'sweets',
    name: 'Sweet Treats',
    itemCount: 21,
    image:
      'https://images.unsplash.com/photo-1481391319762-47dff72954d9?auto=format&fit=crop&w=700&q=80',
  },
];

export const products: HomeProduct[] = [
  {
    id: 'truffle-popcorn',
    slug: 'black-truffle-popcorn',
    name: 'Black Truffle Popcorn',
    category: 'Gourmet Popcorn',
    subCategory: 'Savory Popcorn',
    brand: 'SnackCo Reserve',
    sku: 'SNK-POP-TRF-090',
    description:
      'Small-batch mushroom popcorn tossed with black truffle seasoning, cheddar notes, and a clean sea-salt finish.',
    ingredients: ['Mushroom corn', 'Sunflower oil', 'Black truffle seasoning', 'Cheddar powder', 'Sea salt'],
    weight: '90 g',
    nutritionFacts: {
      servingSize: '30 g',
      calories: 142,
      protein: '3 g',
      carbs: '18 g',
      fat: '7 g',
      sugar: '1 g',
      sodium: '210 mg',
    },
    mrp: 299,
    discount: 17,
    offerPrice: 249,
    price: 249,
    compareAtPrice: 299,
    stock: 'in_stock',
    availableQuantity: 42,
    tags: ['truffle', 'popcorn', 'vegetarian', 'movie night'],
    rating: 4.9,
    reviews: 186,
    averageRating: 4.9,
    reviewCount: 186,
    isFeatured: true,
    isTrending: false,
    isBestSeller: true,
    recommendedProductIds: ['sea-salt-caramel', 'nacho-combo'],
    relatedProductIds: ['peri-peri-crisps', 'festive-snack-box'],
    deliveryEstimate: 'Arrives in 2-4 business days',
    returnPolicy: 'Eligible for replacement within 3 days if sealed pack is damaged.',
    shippingInformation: 'Ships in a recyclable sealed pouch with tamper-proof outer packaging.',
    badge: 'Best seller',
    image:
      'https://images.unsplash.com/photo-1578849278619-e73505e9610f?auto=format&fit=crop&w=900&q=85',
    images: [
      {
        id: 'truffle-1',
        url: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f?auto=format&fit=crop&w=1200&q=90',
        publicId: 'snackco/products/truffle-popcorn/front',
        alt: 'Black truffle popcorn in a bowl',
      },
      {
        id: 'truffle-2',
        url: 'https://images.unsplash.com/photo-1585647347483-22b66260dfff?auto=format&fit=crop&w=1200&q=90',
        publicId: 'snackco/products/truffle-popcorn/texture',
        alt: 'Close up of seasoned popcorn kernels',
      },
      {
        id: 'truffle-3',
        url: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?auto=format&fit=crop&w=1200&q=90',
        publicId: 'snackco/products/truffle-popcorn/serve',
        alt: 'Popcorn served for a movie night',
      },
    ],
    customerReviews: [
      {
        id: 'truffle-review-1',
        name: 'Rhea K.',
        rating: 5,
        title: 'Premium and fresh',
        comment: 'The truffle flavor is bold without feeling heavy. Great seal and crunch.',
        createdAt: '2026-06-18',
      },
      {
        id: 'truffle-review-2',
        name: 'Kabir S.',
        rating: 5,
        title: 'Movie night upgrade',
        comment: 'Way better than regular popcorn and the pack stayed crisp after opening.',
        createdAt: '2026-06-21',
      },
    ],
  },
  {
    id: 'peri-peri-crisps',
    slug: 'peri-peri-crunch-crisps',
    name: 'Peri Peri Crunch Crisps',
    category: 'Crisps & Chips',
    subCategory: 'Spicy Crisps',
    brand: 'Crunch Lab',
    sku: 'SNK-CHP-PRP-075',
    description:
      'Thin-cut potato crisps layered with smoky peri peri spice, lemon tang, and a long crunchy finish.',
    ingredients: ['Potato flakes', 'Rice bran oil', 'Peri peri spice', 'Lemon powder', 'Iodized salt'],
    weight: '75 g',
    nutritionFacts: {
      servingSize: '25 g',
      calories: 133,
      protein: '2 g',
      carbs: '14 g',
      fat: '8 g',
      sugar: '2 g',
      sodium: '260 mg',
    },
    mrp: 179,
    discount: 17,
    offerPrice: 149,
    price: 149,
    compareAtPrice: 179,
    stock: 'in_stock',
    availableQuantity: 64,
    tags: ['spicy', 'crisps', 'chips', 'party'],
    rating: 4.7,
    reviews: 142,
    averageRating: 4.7,
    reviewCount: 142,
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    recommendedProductIds: ['nacho-combo', 'truffle-popcorn'],
    relatedProductIds: ['sea-salt-caramel', 'berry-trail-mix'],
    deliveryEstimate: 'Arrives in 2-5 business days',
    returnPolicy: 'Eligible for replacement within 3 days for damaged sealed packs.',
    shippingInformation: 'Packed in a nitrogen-flushed pouch and shipped in crush-resistant mailers.',
    badge: 'Trending',
    image:
      'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=900&q=85',
    images: [
      {
        id: 'peri-1',
        url: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=1200&q=90',
        publicId: 'snackco/products/peri-peri-crisps/front',
        alt: 'Peri peri crisps in a bowl',
      },
      {
        id: 'peri-2',
        url: 'https://images.unsplash.com/photo-1613919113640-25732ec5e61f?auto=format&fit=crop&w=1200&q=90',
        publicId: 'snackco/products/peri-peri-crisps/texture',
        alt: 'Spiced potato crisps close up',
      },
    ],
    customerReviews: [
      {
        id: 'peri-review-1',
        name: 'Dev M.',
        rating: 5,
        title: 'Proper heat',
        comment: 'Spicy, crisp, and not oily. The lemon note is excellent.',
        createdAt: '2026-06-10',
      },
    ],
  },
  {
    id: 'berry-trail-mix',
    slug: 'berry-protein-trail-mix',
    name: 'Berry Protein Trail Mix',
    category: 'Nuts & Trail Mix',
    subCategory: 'Protein Mixes',
    brand: 'NutriTrail',
    sku: 'SNK-NUT-BRY-120',
    description:
      'Roasted almonds, cashews, pumpkin seeds, dried berries, and dark chocolate chips for a balanced snack break.',
    ingredients: ['Almonds', 'Cashews', 'Pumpkin seeds', 'Dried cranberries', 'Dark chocolate chips'],
    weight: '120 g',
    nutritionFacts: {
      servingSize: '40 g',
      calories: 188,
      protein: '7 g',
      carbs: '16 g',
      fat: '11 g',
      sugar: '6 g',
      sodium: '75 mg',
    },
    mrp: 329,
    discount: 0,
    offerPrice: 329,
    price: 329,
    stock: 'low_stock',
    availableQuantity: 9,
    tags: ['protein', 'nuts', 'trail mix', 'travel'],
    rating: 4.8,
    reviews: 98,
    averageRating: 4.8,
    reviewCount: 98,
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    recommendedProductIds: ['festive-snack-box', 'truffle-popcorn'],
    relatedProductIds: ['peri-peri-crisps', 'sea-salt-caramel'],
    deliveryEstimate: 'Arrives in 3-5 business days',
    returnPolicy: 'Food safety policy allows replacement only for damaged or incorrect sealed products.',
    shippingInformation: 'Resealable pouch shipped with moisture-safe packaging.',
    badge: 'New',
    image:
      'https://images.unsplash.com/photo-1599599810694-b5b37304c041?auto=format&fit=crop&w=900&q=85',
    images: [
      {
        id: 'berry-1',
        url: 'https://images.unsplash.com/photo-1599599810694-b5b37304c041?auto=format&fit=crop&w=1200&q=90',
        publicId: 'snackco/products/berry-trail-mix/front',
        alt: 'Berry protein trail mix',
      },
      {
        id: 'berry-2',
        url: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e4?auto=format&fit=crop&w=1200&q=90',
        publicId: 'snackco/products/berry-trail-mix/ingredients',
        alt: 'Nuts and dried fruit ingredients',
      },
    ],
    customerReviews: [
      {
        id: 'berry-review-1',
        name: 'Isha R.',
        rating: 5,
        title: 'Great desk snack',
        comment: 'Good mix of nuts and berries. Not too sweet.',
        createdAt: '2026-06-16',
      },
    ],
  },
  {
    id: 'sea-salt-caramel',
    slug: 'sea-salt-caramel-bites',
    name: 'Sea Salt Caramel Bites',
    category: 'Sweet Treats',
    subCategory: 'Caramel Bites',
    brand: 'Sweet Barrel',
    sku: 'SNK-SWT-SSC-100',
    description:
      'Soft caramel bites finished with flaky sea salt and packed in a resealable pouch for sharing.',
    ingredients: ['Sugar', 'Milk solids', 'Butter', 'Sea salt', 'Vanilla extract'],
    weight: '100 g',
    nutritionFacts: {
      servingSize: '25 g',
      calories: 118,
      protein: '1 g',
      carbs: '21 g',
      fat: '4 g',
      sugar: '17 g',
      sodium: '90 mg',
    },
    mrp: 249,
    discount: 20,
    offerPrice: 199,
    price: 199,
    compareAtPrice: 249,
    stock: 'in_stock',
    availableQuantity: 37,
    tags: ['caramel', 'sweet', 'gifting', 'vegetarian'],
    rating: 4.9,
    reviews: 211,
    averageRating: 4.9,
    reviewCount: 211,
    isFeatured: true,
    isTrending: false,
    isBestSeller: true,
    recommendedProductIds: ['truffle-popcorn', 'festive-snack-box'],
    relatedProductIds: ['berry-trail-mix', 'nacho-combo'],
    deliveryEstimate: 'Arrives in 2-4 business days',
    returnPolicy: 'Replacement available for damaged sealed products within 3 days of delivery.',
    shippingInformation: 'Temperature-aware packaging used during warm weather windows.',
    badge: "Today's deal",
    image:
      'https://images.unsplash.com/photo-1481391319762-47dff72954d9?auto=format&fit=crop&w=900&q=85',
    images: [
      {
        id: 'caramel-1',
        url: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?auto=format&fit=crop&w=1200&q=90',
        publicId: 'snackco/products/sea-salt-caramel/front',
        alt: 'Sea salt caramel bites',
      },
      {
        id: 'caramel-2',
        url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=90',
        publicId: 'snackco/products/sea-salt-caramel/serve',
        alt: 'Sweet bites served on a table',
      },
    ],
    customerReviews: [
      {
        id: 'caramel-review-1',
        name: 'Maya P.',
        rating: 5,
        title: 'Perfect sweet finish',
        comment: 'Soft caramel, balanced salt, and lovely packaging.',
        createdAt: '2026-06-13',
      },
    ],
  },
  {
    id: 'nacho-combo',
    slug: 'loaded-nacho-party-combo',
    name: 'Loaded Nacho Party Combo',
    category: 'Combo Offers',
    subCategory: 'Party Combos',
    brand: 'SnackCo Reserve',
    sku: 'SNK-CMB-NCH-420',
    description:
      'A party-ready combo with nacho chips, salsa-style seasoning, cheesy dip mix, and spicy crunch packs.',
    ingredients: ['Corn chips', 'Cheese seasoning', 'Tomato spice blend', 'Jalapeno powder', 'Sea salt'],
    weight: '420 g',
    nutritionFacts: {
      servingSize: '50 g',
      calories: 236,
      protein: '5 g',
      carbs: '31 g',
      fat: '10 g',
      sugar: '3 g',
      sodium: '410 mg',
    },
    mrp: 699,
    discount: 21,
    offerPrice: 549,
    price: 549,
    compareAtPrice: 699,
    stock: 'in_stock',
    availableQuantity: 22,
    tags: ['combo', 'party', 'nachos', 'sharing'],
    rating: 4.6,
    reviews: 74,
    averageRating: 4.6,
    reviewCount: 74,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    recommendedProductIds: ['peri-peri-crisps', 'truffle-popcorn'],
    relatedProductIds: ['festive-snack-box', 'sea-salt-caramel'],
    deliveryEstimate: 'Arrives in 3-5 business days',
    returnPolicy: 'Replacement available for damaged combo contents reported within 3 days.',
    shippingInformation: 'Multi-pack box with inner cushioning for party packs.',
    badge: 'Combo',
    image:
      'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=900&q=85',
    images: [
      {
        id: 'nacho-1',
        url: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=1200&q=90',
        publicId: 'snackco/products/nacho-combo/front',
        alt: 'Loaded nacho party combo',
      },
      {
        id: 'nacho-2',
        url: 'https://images.unsplash.com/photo-1618040996337-56904b7850b9?auto=format&fit=crop&w=1200&q=90',
        publicId: 'snackco/products/nacho-combo/spread',
        alt: 'Nachos and dips party spread',
      },
    ],
    customerReviews: [
      {
        id: 'nacho-review-1',
        name: 'Aman G.',
        rating: 4,
        title: 'Good party box',
        comment: 'Enough variety for a small get-together and good crunch.',
        createdAt: '2026-06-09',
      },
    ],
  },
  {
    id: 'festive-snack-box',
    slug: 'festive-snack-box',
    name: 'Festive Snack Box',
    category: 'Seasonal Offers',
    subCategory: 'Gift Boxes',
    brand: 'SnackCo Reserve',
    sku: 'SNK-BOX-FST-650',
    description:
      'A premium gift box with sweet, spicy, and savory snack packs selected for seasonal celebrations.',
    ingredients: ['Assorted popcorn', 'Roasted nuts', 'Caramel bites', 'Spiced crisps', 'Chocolate clusters'],
    weight: '650 g',
    nutritionFacts: {
      servingSize: '50 g',
      calories: 221,
      protein: '4 g',
      carbs: '28 g',
      fat: '11 g',
      sugar: '12 g',
      sodium: '220 mg',
    },
    mrp: 1099,
    discount: 18,
    offerPrice: 899,
    price: 899,
    compareAtPrice: 1099,
    stock: 'in_stock',
    availableQuantity: 15,
    tags: ['gift box', 'seasonal', 'festival', 'assorted'],
    rating: 4.9,
    reviews: 56,
    averageRating: 4.9,
    reviewCount: 56,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    recommendedProductIds: ['sea-salt-caramel', 'berry-trail-mix'],
    relatedProductIds: ['nacho-combo', 'truffle-popcorn'],
    deliveryEstimate: 'Arrives in 3-6 business days',
    returnPolicy: 'Gift boxes can be replaced only for transit damage or incorrect items.',
    shippingInformation: 'Ships in a rigid gift box with protective outer carton.',
    badge: 'Seasonal',
    image:
      'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?auto=format&fit=crop&w=900&q=85',
    images: [
      {
        id: 'festive-1',
        url: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?auto=format&fit=crop&w=1200&q=90',
        publicId: 'snackco/products/festive-snack-box/front',
        alt: 'Festive snack gift box',
      },
      {
        id: 'festive-2',
        url: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?auto=format&fit=crop&w=1200&q=90',
        publicId: 'snackco/products/festive-snack-box/open',
        alt: 'Opened assorted snack box',
      },
    ],
    customerReviews: [
      {
        id: 'festive-review-1',
        name: 'Priya N.',
        rating: 5,
        title: 'Gift-ready',
        comment: 'Sent this to family and they loved the variety and packaging.',
        createdAt: '2026-06-24',
      },
    ],
  },
];

export const reviews: Review[] = [
  {
    id: 'rhea',
    name: 'Rhea Kapoor',
    role: 'Verified buyer',
    rating: 5,
    quote:
      'The caramel popcorn tastes premium, arrives fresh, and the packaging feels gift-ready.',
  },
  {
    id: 'arjun',
    name: 'Arjun Mehta',
    role: 'Corporate gifting',
    rating: 5,
    quote:
      'We ordered combo boxes for our team. Smooth checkout, quick delivery, excellent variety.',
  },
  {
    id: 'naina',
    name: 'Naina Shah',
    role: 'Snack subscriber',
    rating: 5,
    quote:
      'The best part is discovering new flavors without losing the familiar comfort snacks.',
  },
];

export const brands = ['SnackCo Reserve', 'Kernel Craft', 'Crunch Lab', 'NutriTrail', 'Sweet Barrel'];

export const galleryImages: GalleryImage[] = [
  {
    id: 'gallery-popcorn',
    alt: 'Caramel popcorn served in a ceramic bowl',
    src: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 'gallery-chips',
    alt: 'Crispy chips with seasoning',
    src: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 'gallery-mix',
    alt: 'Trail mix with nuts and berries',
    src: 'https://images.unsplash.com/photo-1599599810694-b5b37304c041?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 'gallery-gift',
    alt: 'Packed snack gift box',
    src: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?auto=format&fit=crop&w=500&q=80',
  },
];
