export const ROUTES = {
  home: '/',
  products: '/products',
  cart: '/cart',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  profile: '/profile',
  checkout: '/checkout',
  orders: '/orders',
  orderDetail: (id: string) => `/orders/${id}`,
  wishlist: '/wishlist',
  adminDashboard: '/admin/dashboard',
  adminOrders: '/admin/orders',
  adminOrderDetail: (id: string) => `/admin/orders/${id}`,
  adminCoupons: '/admin/coupons',
  adminProducts: '/admin/products',
  adminProductNew: '/admin/products/new',
  adminProductEdit: (id: string) => `/admin/products/${id}/edit`,
  adminInventory: '/admin/inventory',
  adminCategories: '/admin/categories',
  adminCustomers: '/admin/customers',
  adminCustomerDetail: (id: string) => `/admin/customers/${id}`,
  adminReviews: '/admin/reviews',
  about: '/about',
  contact: '/contact',
  faq: '/faq',
  privacy: '/privacy',
  terms: '/terms',
  refundPolicy: '/refund-policy',
  shippingPolicy: '/shipping-policy',
  careers: '/careers',
  blog: '/blog',
  compare: '/compare',
} as const;
