export const ROUTES = {
  home: '/',
  products: '/products',
  cart: '/cart',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  profile: '/profile',
  checkout: '/checkout',
  orders: '/orders',
  orderDetail: (id: string) => `/orders/${id}`,
  wishlist: '/wishlist',
  adminDashboard: '/admin/dashboard',
} as const;
